apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
        - name: backstage
          image: samdudgeon692/backstage-app:latest
          ports:
            - containerPort: 7000
          env:
            - name: NODE_ENV
              value: production
          volumeMounts:
            - name: backstage-config
              mountPath: /app/app-config.yaml
              subPath: app-config.yaml
      volumes:
        - name: backstage-config
          configMap:
            name: backstage-config
